---

- name: Download Kafka
  get_url:
    url: "http://www-us.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/tmp/kafka_{{ kafka_version }}.tgz"

- name: Extract Kafka
  unarchive:
    src: "/tmp/kafka_{{ kafka_version }}.tgz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/kafka_{{ kafka_version }}"

...
