---

- include_tasks: ./install_deps_ubuntu.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: ./install_confluent_ubuntu.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_tasks: ./install_kafka.yaml

- include_tasks: ./kafka_ssl.yaml
  when: kafka_inter_broker == ssl or kafka_auth_client == ssl

- include_tasks: ./kafka_configure.yaml

...
