---

- name: Install Java
  apt:
    name: openjdk-8-jdk
    state: present

- name: Download Kafka
  get_url:
    url: "http://www-us.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/tmp/kafka_{{ kafka_version }}.tgz"

- name: Extract Kafka
  unarchive:
    src: "/tmp/kafka_{{ kafka_version }}.tgz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/kafka_{{ kafka_version }}"

- name: Configure Kafka
  template:
    src: "server.properties.j2"
    dest: "/opt/kafka_{{ kafka_version }}/config/server.properties"

- name: Start Kafka
  command: "/opt/kafka_{{ kafka_version }}/bin/kafka-server-start.sh /opt/kafka_{{ kafka_version }}/config/server.properties"

...
